import type { Metadata, Viewport } from "next";

import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import {nunitoSans } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};
export const viewport: Viewport = {
  width:"device-width",
  initialScale: 1,

}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
             __html: `(() => {
  try {
    const theme = localStorage.getItem('theme');
    const isDark = theme === 'dark';
    document.documentElement.classList.toggle('dark', isDark);
  } catch (_) {}
})();`,

          }}
        />
      </head>
      <body className={`${nunitoSans.variable} font-nunito-sans antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );

}
