import type { Metadata, Viewport } from "next";

import DashboardNavbar from "@/components/dashboard/LinksSettingsTabs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <>
      <DashboardNavbar/>
      <main>{children}</main>
    </>
  );
}
